### ISSUE TITLE
index.html has broken path to assets/app.js

### ISSUE THREAD

**Issue by tylerjryan** [react-webpack-generators/generator-react-webpack#233]
In `src/index.html`, the `app.js` file is sourced by this line here:

```
  <script type="text/javascript" src="/assets/app.js"></script>
```

When opening the `dist/index.html` file after running `npm run dist`, I am seeing this error in the console:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND ...  file:///assets/app.js
```

I fixed this by simply changing the src path to:

```
  <script type="text/javascript" src="./assets/app.js"></script>
```

Notice the addition of the "." in front of `/assets`.

**Comment by weblogixx** [comment]
HI @tylerjryan,

we just changed the path of assets/app.js to be absolute instead of relative. This is needed because when using react router with deep routes, app.js cannot be found. I will have a look at how to fix this for both dev and live versions.

**Comment by tylerjryan** [comment]
Thank you!
