### ISSUE TITLE
env variables not passed through

### ISSUE THREAD

**Issue by cheshire137** [react-webpack-generators/generator-react-webpack#260]
I'm trying to modify src/config/base.js to include an environment variable value like so:

```javascript
export default {
  auth: {
    id: process.env.CLIENT_ID
  }
}
```

However, `id` is always `undefined`. I can `console.log(process.env);` in server.js and I see the CLIENT_ID environment variable as expected. So something strips it out before it makes it to the app, thus I'm not sure where configuration should live.

**Comment by sthzg** [comment]
hi @cheshire137 I do this by using Webpack's [DefinePlugin](https://webpack.github.io/docs/list-of-plugins.html#defineplugin) to make selected (env) variables available.

In the current generator version (the config system is refactored for the upcoming V4 release) you will have to modify these files:

- [`cfg/dev.js`](https://github.com/weblogixx/react-webpack-template/blob/v1.7.1/cfg/dev.js#L19)
- [`cfg/dist.js`](https://github.com/weblogixx/react-webpack-template/blob/v1.7.1/cfg/dist.js#L18-L20)
- [`cfg/test.js`](https://github.com/weblogixx/react-webpack-template/blob/v1.7.1/cfg/test.js#L53)

Search for the `plugins` array (the above links are linked to the line numbers in the current release) and add or modify the `DefinePlugin()` entry to include a key/value of `'process.env.CLIENT_ID': JSON.stringify(process.env.CLIENT_ID)`:

```js
new webpack.DefinePlugin({
  'process.env.CLIENT_ID': JSON.stringify(process.env.CLIENT_ID)
}),
```

`cfg/dev.js` for example might look like:

```js
plugins: [
  new webpack.HotModuleReplacementPlugin(),
  new webpack.NoErrorsPlugin(),
  new webpack.DefinePlugin({
    'process.env.CLIENT_ID': JSON.stringify(process.env.CLIENT_ID)
  }),
  new BowerWebpackPlugin({
    searchResolveModulesDirectories: false
  })
],
```

This way, Webpack exposes the system's env value for a specific key to the code that is transpiled into a bundle. Thus your reference in `src/config/base.js` should no longer be `undefined`, but use the value of `process.env.CLIENT_ID`.

**Comment by sthzg** [comment]
@cheshire137 I will close this issue due to inactivity for now, feel free to re-open it anytime if you have further questions.
