### ISSUE TITLE
enzyme usage

### ISSUE THREAD

**Issue by be-codified** [react-webpack-generators/generator-react-webpack#274]
Hi,

is there any simple way to use [enzyme](https://github.com/airbnb/enzyme) within your generator?

**Comment by sthzg** [comment]
Hi @be-codified, for integration into the current stable release @weblogixx summed it up here https://github.com/react-webpack-generators/generator-react-webpack/issues/256#issuecomment-233230142 

It's also worth mentioning that the upcoming V4 release (can be installed with npm install generator-react-webpack@beta) comes with enzyme integrated automatically.

**Comment by be-codified** [comment]
Great, thank you.
