### ISSUE TITLE
Refactor arrow functions to function() in test template

### ISSUE THREAD

**Issue by sthzg** [react-webpack-generators/generator-react-webpack#275]
As Mocha's official docs [discourage the use of arrow functions](https://mochajs.org/#arrow-functions) in tests, we should rewrite the test template to use inline functions.

> Passing arrow functions (“lambdas”) to Mocha is discouraged. Due to the lexical binding of this, such functions are unable to access the Mocha context. For example, the following code will fail due to the nature of lambdas. [...] If you do not need to use Mocha’s context, lambdas should work. However, the result will be more difficult to refactor if the need eventually arises.

The change would affect 
- [V3 tests/Base.js](https://github.com/react-webpack-generators/generator-react-webpack/blob/master/generators/component/templates/3/tests/Base.js)
- [V4 tests/Base.js](https://github.com/react-webpack-generators/generator-react-webpack/blob/master/generators/component/templates/4/tests/Base.js)

**Examples**

`test/.eslintrc`

```json
{
  "env": {
    "mocha": true
  },
  "rules": {
    "prefer-arrow-callback": "off",
    "func-names": "off"
  },
  "globals": {
    "expect": true
  }
}
```

Some V4 test

```js
import React from 'react';
import { shallow } from 'enzyme';
import App from 'components/App';

describe('<App />', function () {

  beforeEach(function () {
    this.component = shallow(<App />);
  });

  describe('when rendering the component', function () {

    it('should have a className of "index"', function () {
      expect(this.component.hasClass('index')).to.equal(true);
    });
  });
});
```

**Comment by weblogixx** [comment]
@sthzg: Interesting, I did not know that. I havent had any issues with this, either. However, I too think we should stick to the recommendations. 👍
