### ISSUE TITLE
Module build failed: Error: Cannot find module 'eslint-config-airbnb'

### ISSUE THREAD

**Issue by kauegimenes** [react-webpack-generators/generator-react-webpack#277]
```
ERROR in ./src/index.js
Module build failed: Error: Cannot find module 'eslint-config-airbnb'
```

**Comment by JakeBernstein65** [comment]
How did you fix this problem? I've been having the same error for the past two day. Thanks!

**Comment by kauegimenes** [comment]
there was a .eslint hidden file in my home folder (1 dir up of the react project)

**Comment by JakeBernstein65** [comment]
Did you just delete it to fix the problem?

**Comment by kauegimenes** [comment]
yes

**Comment by JakeBernstein65** [comment]
Thanks for the advice! I figured out that yeoman installed a lot of hidden dot (.) files in my home directory instead of project directory and this is what was messing up my installation.
