### ISSUE TITLE
V4 -- Provide sub generator to insert new env

### ISSUE THREAD

**Issue by sthzg** [react-webpack-generators/generator-react-webpack#278]
I'd like to propose the following and am interested in feedback if that would be considered useful.

``` sh
yo react-webpack:setup:newenv <env_name>
# writes config/webpack/<env_name>.js
# adds export to config/webpack/index.js
# writes src/config/<env_name>.js
# possibly writes to some other places I forgot about right now
```
## Progress
- [x] Write `config/webpack/<env_name>.js`
- [x] Write `src/config/<env_name>.js`
- [x] Add export to `config/webpack/index.js`
- [x] Add basic tests to verify file creation and contents

**Supported options (future iterations):**

Functionality In the initial PR is kept simple to provide quicker integration. Further iterations can provide various finer updates, e.g.

``` sh
--buildable    adds a build:<env_name> run script to package.json
--servable     adds a serve:<env_name> run script to package.json
```

**Motivation:**

In many projects I add one or more additional envs, e.g. a `lib` env that builds various component chunks to separate es5-artifacts.

**File Contents:**

The files it creates are bare-bones, don't make any assumptions, and just provide the boilerplate for users to insert their env configuration, whatever this might be.

**UI:**

The namespace `react-webpack:setup:<foo>` is chosen so that we can add arbitrary setup tools in the future when the use case arises. ATM I don't know if Yeoman can by default resolve a third level, so if that doesn't work easily I would propose `yo react-webpack:setup-<foo>` instead (note the hypen `-` instead of the colon `:`.

**Comment by weblogixx** [comment]
Sounds like a good idea 👍

**Comment by sthzg** [comment]
@weblogixx I've pushed the initial version for this feature in https://github.com/react-webpack-generators/generator-react-webpack/commit/6fb7f6076ca68e762a85c2395750866a9165d7d1. I'd postpone additional features (e.g. the options proposed in the initial ticket) to a later time. IMO it is valuable even in this very basic state. Let me know what you think.

**Comment by weblogixx** [comment]
Hi @sthzg, sorry for the late reply, I was on vacation. This seems really nice to me. 👍 for also adding it to the global config loader. I think this is fine and should be integrated for v4.

**Comment by sthzg** [comment]
@weblogixx no worries, I hope you had a great vacation. I want to make the first version of the code insertion still a bit more resilient and will then merge it into V4.

**Comment by sthzg** [comment]
Initial functionality provided with #308
