### ISSUE TITLE
Cant open on mobile .

### ISSUE THREAD

**Issue by BigSoviet** [react-webpack-generators/generator-react-webpack#282]
Hello,

I am making mobile version of app using this generator. I have a problem open my application on my phone. I go to 192.168.1.6:8000(my desktop ip in local net on which webpack server is running) on mobile Chrome, but it tells me that site can't be reached. 
In the same time I've tested it on simple express server and everything runs well.

Please, advice.

Best regards, 
Yan.

**Comment by sthzg** [comment]
Hi @BigSoviet, by default the server is bound to localhost, which is only accessible from the same machine.

Please try changing `localhost` [in server.js:#18](https://github.com/react-webpack-generators/react-webpack-template/blob/master/server.js#L18) to `0.0.0.0`. This should* make your app accessible from within your local network. (* If that doesn't work, it could also be a firewall blocking inbound access to your machine.)

**Comment by BigSoviet** [comment]
Thank you very much, your advice has helped.
