### ISSUE TITLE
postcss

### ISSUE THREAD

**Issue by dukegod** [react-webpack-generators/generator-react-webpack#283]
how to support autoprefixer?

just modify cfg/defaults.js!!! 
like :

```
module.exports = {
  srcPath: srcPath,
  publicPath: '/assets/',
  port: dfltPort,
  getDefaultModules: getDefaultModules,
 postcss: function () {
        return [precss, autoprefixer];
    }
};
```

**Comment by dukegod** [comment]
in "cfg/defaults.js" file, "postcss"function will not be work.

**Comment by ajnudnyy** [comment]
Dukegod:
No! No  doesn't modify cfg/defaults.js.
 
As noted, it's to modify cfg/base.js
![image](https://cloud.githubusercontent.com/assets/18208441/20252743/f56e7cdc-aa5f-11e6-8201-f3c1da0ebb93.png)

**Comment by ajnudnyy** [comment]
This process of configuration is noted in markdown file.

**Comment by weblogixx** [comment]
@dukegod: Thank you for your answer. As @ajnudnyy has already noted, the correct place for the v3 generator is currently base.js. I hope you where able to get it running. Please feel free to reopen this issue if there are still any problems.
