### ISSUE TITLE
App View unresponsive

### ISSUE THREAD

**Issue by achang28** [react-webpack-generators/generator-react-webpack#284]
From picture below, the "TEsting" button and input field are both unresponsive.  The button does not even press, nor can data be inputed into input field.

Is the "App ready" header supposed to be there?

![testing](https://cloud.githubusercontent.com/assets/3760499/18109380/d92d90f6-6ec5-11e6-8893-94c75a46d828.png)

**Comment by 3terrace** [comment]
Do you have Python installed on your computer？Maybe you lack it.






------------------ 原始邮件 ------------------
发件人: "Albert Chang";<notifications@github.com>;
发送时间: 2016年8月31日(星期三) 上午6:11
收件人: "react-webpack-generators/generator-react-webpack"<generator-react-webpack@noreply.github.com>; 

主题: [react-webpack-generators/generator-react-webpack] App Viewunresponsive (#284)




When rendering buttons, input fields, etc., none of these can be interacted with.  In other words, buttons don't do anything when pressed (they don't even have the appearance of being pressed), nor can I type anything within the input fields.

**Comment by achang28** [comment]
@3terrace I do have Python installed; but that shouldn't have anything to do with getting this app up and running w/ it.  Simply generating a stubbed out project, and then adding a simple button in any of the HTML files should allow it to be pressed.

**Comment by achang28** [comment]
Solved the problem by a simple solution:  https://github.com/react-webpack-generators/generator-react-webpack/issues/280
