### ISSUE TITLE
Option to use React.createClass

### ISSUE THREAD

**Issue by jordyvandomselaar** [react-webpack-generators/generator-react-webpack#285]
I'd like to have a setting that allows me to use React.createClass rather than extends. Would this be ok?

**Comment by weblogixx** [comment]
Hi @jordyvandomselaar,

this would be possible. If there is enough demand we we could maybe implement it into the next major version of the generator.
@sthzg: Whats your opinion on this?

**Comment by sthzg** [comment]
Sorry for the late reply, somehow I missed that one. IMO that is a tough call. I can see how and why it would be valuable, on the other hand it would double the variations on the template generation and on the automated tests. Especially manually testing each possibility would become even more involved than it is already.

Also it may be worth thinking about consequences for external generators like the alt and flux generator, which had to add support as well. I also figure that sometimes there might not always be an easy path to support both worlds.

**Comment by jordyvandomselaar** [comment]
No problem :)
I see, I'll just get used to it then, it's too much work for something that's not a must have to begin with.
Thanks for the replies! :D

**Comment by weblogixx** [comment]
After thinking a bit longer about this, we will currently not implement this feature. Most projects move away vom React.createClass anyways. If the question arises again, we may have another look at it...
