### ISSUE TITLE
Cannot resolve module 'sass-loader': scss generator generates vanilla css file and is missing sass-loader dependency

### ISSUE THREAD

**Issue by neilsarkar** [react-webpack-generators/generator-react-webpack#293]
Steps to reproduce:

## Select scss generator and postcss

<img width="550" alt="foo_ _npm_ _yo_rvm_bin_path__users_neilsarkar__rvm_bin_term_program_apple_terminal_ _158x42" src="https://cloud.githubusercontent.com/assets/83109/19311399/1bc8c2c8-9086-11e6-9ffa-044cb52ddf13.png">

<img width="466" alt="foo_ _-bash_ _158x42" src="https://cloud.githubusercontent.com/assets/83109/19311481/7a97c57e-9086-11e6-8ea5-84d4adda1cc4.png">

## Adding an scss file results in loading error

<img width="1263" alt="localhost_8000_webpack-dev-server_" src="https://cloud.githubusercontent.com/assets/83109/19311539/c3a4da68-9086-11e6-8e9f-740749830910.png">

## Workaround

1. Rename `App.css` to `App.scss`
2. Change reference from `App.css` to `App.scss` in `Main.js`
3. Install sass-loader

```bash
$ npm install --save-dev node-sass sass-loader
```

4. Restart webpack server with `npm start`

**Comment by oktalk** [comment]
I couldn't get your workaround to work. We need a fix for this.

**Comment by neilsarkar** [comment]
forked to inspect and this appears to be fixed on master. closing.
