### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by JohnyFreeze** [react-webpack-generators/generator-react-webpack#295]
Hi, 
I wanna ask if you have prepared solution for production.For example delete hot reloading or create webpack build and so on..

Thanks for answer

**Comment by sthzg** [comment]
Hi @JohnyFreeze, if you run `npm run dist` the buid will be optimized for production. This includes invoking webpack with the `-p` option, building the app with `NODE_ENV` `production`, leaving out hot module replacement, and making use of some further Webpack plugins. 

You can take a look at [`cfg/Dist.js`](https://github.com/react-webpack-generators/react-webpack-template/blob/master/cfg/dist.js) to see the Webpack config that is used for `npm run dist`.
