### ISSUE TITLE
removing live reload header

### ISSUE THREAD

**Issue by chriswingler** [react-webpack-generators/generator-react-webpack#299]
Hi, I would like to remove the live reload header, but can't find any reference to it.  Is there a simple, clean way to do this?

**Comment by sthzg** [comment]
Hi @chriswingler, you can open your page without the `webpack-dev-server` in the path (i.e. instead of `http://localhost:8000/webpack-dev-server/` just `http://localhost:8000/`). This should show your app without the live reload header.

**Comment by sthzg** [comment]
I am closing this for now, feel free to comment on it if it hasn't been resolved.
