### ISSUE TITLE
Separating runnable item the from host Item

### ISSUE THREAD

**Issue by ajnudnyy** [react-webpack-generators/generator-react-webpack#300]
I propose to deploy my site on servers that I just finished, but our servers installed java + tomcat  for run java code and response, which isn't support of num running.

So I was wandering whether the runnable item could be separated from host Item and seek out?

**Comment by ajnudnyy** [comment]
I'm looking forward for your reply,  our first page is going to go live ?  
thank you  pretty much.

**Comment by AlexandreKilian** [comment]
you can run react client-side no matter what kind of server is delivering the assets (it that was the question you hab). You won't be able to use serverside rendering though

**Comment by ajnudnyy** [comment]
Got it. I dont fear serverside rendering which  lay-off, I just wander the step by step  operation in dedail.
**who had exaprienced in it could give me a hand?**

**Comment by ajnudnyy** [comment]
Got it. I dont fear serverside rendering which lay-off,
Now I'm trying to deploy a react module on tomcat for testing that I have completed. So the react module need to be separated from folder about yeoman, or other ways is also without any influence Only if the resource can be normally accessed.
 I just wander the dedail of operation that someone separates step by step runnable item from entire project after finished all of chunks.
who had exaprienced in it could give me a hand?

**Comment by ajnudnyy** [comment]
I'm so frustrated with this problem and would appreciate it a lot if someone help me, Thank!

**Comment by ajnudnyy** [comment]
I get it, the runnable static files what I want that would be generated In  the /dist after run npm run dist. 
It's no problem to see the module that I completed by introducing assets/app.js.

**Comment by weblogixx** [comment]
Hi @ajnudnyy,

yes, we do not have a static server in the generator, at least nothing that should/could be used to serve the project in live environments. The webpack-dev-server is used to create a local http-server when you use ```npm start``` or ```npm run serve:dist```. However, to serve your files, you will have to serve the full bundle (generated via ```npm run dist``` with a "real" webserver, e.g. Apache, nginx etc... Hope this clarification helps. As @sthzg posted, we will add simple deployment instructions to the generators README.md file.

Please feel free to reopen this issue if you have any more questions.
