### ISSUE TITLE
React 15.4 breaking changes

### ISSUE THREAD

**Issue by stylesuxx** [react-webpack-generators/generator-react-webpack#302]
I got a report [here](https://github.com/stylesuxx/generator-react-webpack-redux/issues/55) and found some [SO discussion](http://stackoverflow.com/questions/40652327/module-not-found-error-cannot-resolve-module-react-lib-reactmount).

The newest version of react seems to break the gen.

Temp fix is to use 15.3.0 or older:

    npm install react@15.3.0

Seems to be related to **react-hot-loader**. Upgrading to react-hot-loader v3 should fix the problem, good that it is in beta -_-

**Comment by sthzg** [comment]
Thanks for reporting. Also a bit of context on Github https://github.com/gaearon/react-hot-loader/issues/417.

As the author of react-hot-loader states [here](https://github.com/gaearon/react-hot-loader/issues/417#issuecomment-260995694) that the stable 1.x hasn't received updates in a while and he considers 3.x to be more stable, do you have any objections to updating gen and template (both v3 and v4) to react hot loader v3? 

I've setup RHL3 a few times in the past weeks, so I think it shouldn't take much time to get a PR ready for review.

/cc @weblogixx

**Comment by stylesuxx** [comment]
I am all for this changes - I am depending on your version 4, so an update would benefit me a lot - getting quite the issues lately. Let me know how I can help.

**Comment by phellipeandrade** [comment]
Temp Fix with using react 15.4.0

// Render the main component into the dom
ReactDOM.render(<App />, document.getElementById('app'));

if (module.hot) {
  module.hot.accept('./components/Main', () => {
     const NextApp = require('./components/Main').default;
    ReactDOM.render(
         <NextApp />, document.getElementById('app'));
  });
}

**Comment by weblogixx** [comment]
Hi,

I am currently migrating some projects to react-hot-loader@3, if it seems stable enough, I will update the template with it (V3 and V4)

**Comment by sthzg** [comment]
FYI: I have included the workaround (webpack alias to the new `ReactMount` location) into the `v1.7.3` release of the template repo. This fixes installing/running the stable 3.x generator. Once the long-term solution discussed here and in @stylesuxx 's PR we could remove that alias again, but I feel that it was important to provide users of the 3.x line with a quick solution.

More info
- [changeset between 1.7.2 and 1.7.3](https://github.com/react-webpack-generators/react-webpack-template/compare/v1.7.2...v1.7.3)
- [release notes](https://github.com/react-webpack-generators/react-webpack-template/releases/tag/v1.7.3)

**Comment by sthzg** [comment]
Fixed now as follows:

- the stable v3.x series continues using the stable RHL1.x and uses a Webpack alias to accommodate for the new location of `ReactMount`
- the v4.x series has been updated to use RHL3.x.beta

Thanks for your patience and contributions.
