### ISSUE TITLE
Can not resolve module 'ReactMount'

### ISSUE THREAD

**Issue by popingpaul** [react-webpack-generators/generator-react-webpack#303]
erro:"Can not resolve module 'ReactMount'"
when I use 'npm start' run the app first time .

**Comment by motleydev** [comment]
I just started getting this today too, I've been using the generator for about a month with no issues

**Comment by arvinsingla** [comment]
Tried this generator for the first time today and getting this same issue.

**Comment by sthzg** [comment]
@popingpaul @motleydev thanks for reporting. We're tracking this error in #302 (will close this one as duplicate).

We'll update the generator as soon as possible. Until then the workaround linked in the comment on 302 should fine. Sorry for the inconvenience.

**Comment by stephengao666** [comment]
The same problem. Stuck in this issue for a long time.

**Comment by sthzg** [comment]
@stephengao666 please see the linked workaround in #302 to make it work ATM. Discussion and a PR to fixe these issues is in review, so updates will follow soon.

**Comment by sthzg** [comment]
Closing as duplicate #302 (please continue discussion there)
