### ISSUE TITLE
how to seo

### ISSUE THREAD

**Issue by moxiaobei2** [react-webpack-generators/generator-react-webpack#309]
It's easy to develop code with generator-react-webpack,but how to add seo,when I look at the source code,it's simple.

**Comment by sthzg** [comment]
hi @moxiaobei2, the generator creates client-side code only. We currently do not integrate any solutions to accommodate for SEO. 

The routes you could take for that are either creating static pages from your project at build-time (i.e. when Webpack compiles and creates the output bundle) or to aim for Server Side Rendering (SSR). There are a little bit more details in this issue https://github.com/react-webpack-generators/generator-react-webpack/issues/286#issuecomment-245796460.

As you can see there, we were discussing if and how to integrate it, but it is not a priority right now and its also not clear whether this would align with the design goals of this generator. These goals include to keep it really, really simple and let developers add in what they want and how they want it.

**Comment by moxiaobei2** [comment]
@sthzg thanks so much,hope to interate it quickly~
