### ISSUE TITLE
Adding generator-react-webpack-redux to org?

### ISSUE THREAD

**Issue by sthzg** [react-webpack-generators/generator-react-webpack#312]
Hi @weblogixx, I've talked to @stylesuxx a while ago and he asked about whether to also move the redux generator to this org (there was a bit of conversation in Slack about this, but no answer so far). I thought to bring it up here to get a decision for it (I'd be +1 for it).

**Comment by weblogixx** [comment]
Hi @sthzg and @stylesuxx, that would be wonderful!
@stylesuxx: I have just added you to the organization, you may now just move your repo into the org. Thank you for your longtime support, keep up the good work 👍
